### ISSUE TITLE
XTC-Z6：用小天才输入法无法搜索

### ISSUE THREAD

**Issue by byHydrogen** [XC-Qan/WearBili-BugReport#13]
## 提问前，请现在FAQ或issue列表中搜索您的问题。如果您的问题已经被提交过或者在FAQ中提及，您将不会收到来自开发者的回复。您可以在code页面下关注此仓库，以便接收其他人的提问。
# 一个项填写前，请将括号内容删除，将信息填写在冒号后面。

<br>

**软件版本代码**：1.9.8_1662_201207

**您的设备型号**：小天才 Z6（RAM:512MB）

**是否崩溃**：N

**错误发生时间**：2022.08.08，约08:59

**Bug详细描述**:用小天才自带输入法无法搜索

**能否复现**：Y

**复现步骤**:

1.打开WearBili

2.点左上角的推荐

3.在跳出来的界面点搜索

4.在文本框内用小天才输入法输入文字

5.点击小天才输入法右下角的搜索

**Bug截图(可选)**：

**bug所在页面**：搜索页面

**您的联系方式**：1249221216@qq.com

**Comment by SpaceXC** [comment]
点击输入框左侧的搜索图标也可以搜索
