### ISSUE TITLE
[设备]：[问题简要描述]

### ISSUE THREAD

**Issue by xiaotang12344** [XC-Qan/WearBili-BugReport#2]

**Comment by xiaotang12344** [comment]
> **软件版本代码**：Rel-AL 0.10.0
> 
> **您的设备型号**：小米手表
> 
> **是否崩溃**：N
> 
> **错误发生时间**：N
> 
> **Bug详细描述**: 点赞会导致软件重新扫码登陆
> 
> **能否复现**：Y
> 
> **复现步骤**:
> 
> 1.找一个视频
> 
> 2.点赞
> 
> 3.软件闪退，变成扫码登陆界面
> 
> **bug所在页面**：视频页面
> 
> **您的联系方式**：qq:897137774 (沉默）

**Comment by SpaceXC** [comment]
草？
