### ISSUE TITLE
OW20W2：应用闪退

### ISSUE THREAD

**Issue by byHydrogen** [XC-Qan/WearBili-BugReport#26]
## 提问前，请现在FAQ或issue列表中搜索您的问题。如果您的问题已经被提交过或者在FAQ中提及，您将不会收到来自开发者的回复。您可以在code页面下关注此仓库，以便接收其他人的提问。
# 一个项填写前，请将括号内容删除，将信息填写在冒号后面。

<br>

**软件版本代码**：Rel-AL 0.10.2

**您的设备型号**：OppoWatch二代

**是否崩溃**：Y

**错误发生时间**：2022.08.10，约08:34

[**Bug详细描述**:打开网络就崩溃，附上logcat日志一份
[logcat.txt](https://github.com/XC-Qan/WearBili-BugReport/files/9295590/logcat.txt)

**能否复现**：Y

**复现步骤**:

1.打开WearBili

2.打开网络

3.WearBili崩溃

打开网络后再打开WearBili也会闪退

**Bug截图(可选)**：

**bug所在页面**：WearBili加载/登录界面

**您的联系方式**：1249221216@qq.com

**Comment by 2YiMing** [comment]
和#21重复了哦
