### ISSUE TITLE
OW2：动态内容无法刷新

### ISSUE THREAD

**Issue by hanhan51** [XC-Qan/WearBili-BugReport#3]
## 提问前，请现在FAQ或issue列表中搜索您的问题。如果您的问题已经被提交过或者在FAQ中提及，您将不会收到来自开发者的回复。您可以在code页面下关注此仓库，以便接收其他人的提问

<br>

**软件版本代码**：(e.g. Rel-AL 0.9.2)
Rel-AL 0.10.10
**您的设备型号**：（e.g. OppoWatch二代）
oppowatch二代
**是否崩溃**：（Y/N）
N
**错误发生时间**：（e.g. 2022.08.08，约16:10）
2022.8.8,约5.25
**Bug详细描述**:（e.g. 浏览评论快速滑动时崩溃)(请尽量使用准确，简洁的语言描述问题）
滑动到动态，内容刷新不出来
**能否复现**：（Y/N）
Y
**复现步骤**:

1.点开软件

2.滑到动态

3.

**bug所在页面**：（e.g. 动态下的评论页面）
动态主页面
**您的联系方式**：（可选，uid/qq号码/邮箱均可）
3474200847@qq.com

**Comment by SpaceXC** [comment]
重新写

**Comment by xiaotang12344** [comment]
软件版本代码：
Rel-AL 0.10.0
您的设备型号:   小米手表
是否崩溃：N
错误发生时间：N
Bug详细描述: 点赞会导致软件重新进入扫码登陆界面
能否复现：
Y
复现步骤:

1.随便找一个视频

2.点击点赞按钮


3.软件返回扫码登陆界面
bug所在页面：视频详情页
您的联系方式：qq:897137774
