### ISSUE TITLE
打开软件动态刷新不出来

### ISSUE THREAD

**Issue by hanhan51** [XC-Qan/WearBili-BugReport#4]
## 提问前，请现在FAQ或issue列表中搜索您的问题。如果您的问题已经被提交过或者在FAQ中提及，您将不会收到来自开发者的回复。您可以在code页面下关注此仓库，以便接收其他人的提问。
# 一个项填写前，请将括号内容删除，将信息填写在冒号后面。

<br>

**软件版本代码**：(e.g. Rel-AL 0.9.2)
Rel-AL 0.10.10
**您的设备型号**：（e.g. OppoWatch二代）
oppowatch2
**是否崩溃**：（Y/N）
N
**错误发生时间**：（e.g. 2022.08.08，约16:10）
2022.08.08,约17.25
**Bug详细描述**:（e.g. 浏览评论快速滑动时崩溃)(请尽量使用准确，简洁的语言描述问题）

**能否复现**：（Y/N）
Y
**复现步骤**:

1.打开软件

2.滑动到动态页面

**Bug截图(可选)**：
![IMG_20220808_174044](https://user-images.githubusercontent.com/110809289/183388903-604aaee4-6f02-457c-bc45-7f7b62a7265e.jpg)

**bug所在页面**：（e.g. 动态下的评论页面）
动态
**您的联系方式**：（可选，uid/qq号码/邮箱均可）
3474200847@qq.com

**Comment by SpaceXC** [comment]
朵！拉！退！退！退！
